"""updated colum

Revision ID: 150c2d9e28a0
Revises: 41d1ce433b5b
Create Date: 2024-08-16 00:12:12.621087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150c2d9e28a0'
down_revision: Union[str, None] = '41d1ce433b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify', sa.Column('staff_roles', sa.ARRAY(sa.BigInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verify', 'staff_roles')
    # ### end Alembic commands ###
