"""Add closed_by_user_id and closed_at fields to Report model

Revision ID: 15e6bb672c97
Revises: 3c674cac2b92
Create Date: 2024-08-19 23:54:50.715412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e6bb672c97'
down_revision: Union[str, None] = '3c674cac2b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('closed_by_user_id', sa.BigInteger(), nullable=True))
    op.add_column('reports', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'closed_at')
    op.drop_column('reports', 'closed_by_user_id')
    # ### end Alembic commands ###
