"""Role ID Column to Verification Model

Revision ID: 3c674cac2b92
Revises: c560bcc6bdb3
Create Date: 2024-08-18 21:25:30.111147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c674cac2b92'
down_revision: Union[str, None] = 'c560bcc6bdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify_users', sa.Column('role_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verify_users', 'role_id')
    # ### end Alembic commands ###
