"""Add New Fields to VerifyUsers Model

Revision ID: c560bcc6bdb3
Revises: edfc46b2a597
Create Date: 2024-08-18 17:03:01.849703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c560bcc6bdb3'
down_revision: Union[str, None] = 'edfc46b2a597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verify_users', sa.Column('last_moder_id', sa.BigInteger(), nullable=True))
    op.add_column('verify_users', sa.Column('last_verification_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verify_users', 'last_verification_date')
    op.drop_column('verify_users', 'last_moder_id')
    # ### end Alembic commands ###
