"""Added a reason field to the Report model and removed the Member model

Revision ID: e1cb82327d9e
Revises: 15e6bb672c97
Create Date: 2024-08-20 20:55:33.498432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cb82327d9e'
down_revision: Union[str, None] = '15e6bb672c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'reason')
    # ### end Alembic commands ###
