Embeds:
  Example:
    Author: "Example Author"
    AuthorIcon: "https://i.pinimg.com/736x/86/6b/e4/866be4dc8c9ce51aa87bf07cf3dad15e.jpg"
    AuthorUrl: "https://example.com"
    Title: "Example Title"
    Description: "Example Description"
    Url: "https://example.com"
    Timestamp: true
    Footer: "Ticket System"
    FooterIcon: "https://i.pinimg.com/736x/86/6b/e4/866be4dc8c9ce51aa87bf07cf3dad15e.jpg"
    Thumbnail: "https://i.pinimg.com/736x/86/6b/e4/866be4dc8c9ce51aa87bf07cf3dad15e.jpg"
    Image: "https://i.pinimg.com/736x/86/6b/e4/866be4dc8c9ce51aa87bf07cf3dad15e.jpg"
    Fields:
      - name: "Example Fields"
        value: "Example"
        inline: false
  About:
    Footer: "© {developer-displayname}"
    FooterIcon: "{developer-pfp}"
    Fields:
      - name: "<:developer:1272284487149158450> **Разработчик**"
        value: "{developer-name}"
        inline: True

      - name: "<a:ping:1272284672814223390> **Задержка**"
        value: "{api-ping}"
        inline: True

      - name: "<a:uptime:1272284867660611604> **Время работы системы**"
        value: "{uptime}"
        inline: True

      - name: "<:github:1272285058551775272> **Текущая версия**"
        value: "{version}"
        inline: True

      - name: "<:hash_message:1272285350110433380> Всего сообществ"
        value: "{total-messages}"
        inline: True

      - name: "<:members:1272285358901559326> Всего пользователей"
        value: "{total-users}"
        inline: True

  Help:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "Список команд"
    Fields:
      - name: "**`{prefix}about`**"
        value: "Информация о боте и его авторе"
        inline: True

      - name: "**`{prefix}help`**"
        value: "Показать доступные команды и их описание"
        inline: True

      - name: "**`{prefix}user`**"
        value: "Показать информацию о пользователе"
        inline: True

      - name: "**`{prefix}server`**"
        value: "Показать информацию о сервере"
        inline: True

      - name: "**`{prefix}report`**"
        value: "Сообщить о проблеме или нарушении"
        inline: True

      - name: "**`{prefix}ban`** ┊ <:moderator:1272260923196969134>"
        value: "Забанить пользователя с сервера"
        inline: True

      - name: "**`{prefix}kick`** ┊ <:moderator:1272260923196969134>"
        value: "Исключить пользователя из сервера"
        inline: True

      - name: "**`{prefix}verify`** ┊ <:moderator:1272260923196969134>"
        value: "Верифицировать пользователя на сервере"
        inline: True

      - name: "**`{prefix}newkick`** ┊ <:owner:1273932655028605060>"
        value: "Выгоняйте всех новых пользователей в соответствии с определенным временным промежутком"
        inline: True

      - name: "**`{prefix}newban`** ┊ <:owner:1273932655028605060>"
        value: "Забаньте всех новых пользователей сервера в соответствии с определенным временным промежутком"
        inline : True

      - name: "**`{prefix}mention`** ┊ <:owner:1273932655028605060>"
        value: "Отправляет упоминание новым пользователям, уведомляя их о необходимости пройти верификацию на сервере"
        inline: True

  User:
    Title: "Кто такая {user-displayname}"
    Description: "**Общие сведения**:\n<:profile:1272248323280994345> **Имя**: `{user-displayname}`\n<:space:1272248683903189084><:arrowright:1272249470297440417> ID: {user-id}\n<:birthday:1272250119156404337> **Создание:** {user-creation}\n<:date:1272253126803591290> **Присоединился**: {user-join}\n\n**Информация по Verify Bot**:\n<:verify:1272263865480253632> **Верифицирован?**: {verify-status}\n<:ban:1272608029883502612> **Отказы**: `{verify-rejection}`\n<:moderator:1272260923196969134> **Модератор:** {verify-moderator}\n<:space:1272248683903189084><:arrowright:1272249470297440417> ID: {verify-moderator-id}\n<:time:1272262579393269790> **Время проверки**: {verify-date}"

  Server:
    Title: "Информация о сервере [{guild-name}]"
    Description: "<:profile:1272248323280994345> **Название**: {guild-name}\n<:space:1272248683903189084><:arrowright:1272249470297440417> ID: {guild-id}\n<:ownerguild:1274280914901405739> **Владелец:** {guild-owner}<:ownerguild:1274280914901405739>\n<:birthday:1272250119156404337> **Создание**: {guild-creation}\n<:arrow:1274280332304322611> **Каналы**: `{guild-totalchannels}`\n<:space:1272248683903189084><:text:1274281670459133962> Текстовые: `{guild-totaltext}`\n<:space:1272248683903189084><:vc:1274281659264532591> Голосовые: `{guild-totalvoice}`\n<:memberguild:1274284457779531806> **Участники**: `{total-members-local}`\n<:roles:1274285161256718429> **Роли**: `{guild-totalrole}`"

  Verify:
    Title: "Вы хотите верифицировать {user-displayname}?"
    Description: "**Общие сведения**:\n<:profile:1272248323280994345> **Имя**: `{user-displayname}`\n<:space:1272248683903189084><:arrowright:1272249470297440417> ID: {user-id}\n<:birthday:1272250119156404337> **Создание:** {user-creation}\n<:date:1272253126803591290> **Присоединился**: {user-join}\n<:ban:1272608029883502612> **Отказы**: `{verify-rejection}`"

  VerifySuccess:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:tick:1272260155190546584> Верификация успешна!"
    Description: "{user-mention} успешно прошёл верификацию!"
    Timestamp: True

  UserVerifySuccess:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:tick:1272260155190546584> Верификация успешна!"
    Description: "Поздравляем! Вы успешно прошли верификацию на сервере."
    Timestamp: True

  VerifyRejection:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Верификация отклонена!"
    Description: "{user-mention} не прошёл верификацию."
    Timestamp: True

  UserVerifyRejection:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Верификация отклонена!"
    Description: "К сожалению, ваша верификация была отклонена. Если у вас есть вопросы, обратитесь к модераторам."
    Timestamp: True

  VerifyCancelled:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:roles:1274285161256718429> Верификация отменена!"
    Description: "Процесс верификации {user-mention} был отменён."

  VerifyRemoved:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:tick:1272260155190546584> Верификация удалена!"
    Description: "Верификация пользователя {user-mention} была успешно удалена."
    Timestamp: True

  UserVerifyRemoved:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Верификация удалена!"
    Description: "Ваша верификация была успешно удалена. Если у вас есть вопросы или вы хотите снова пройти верификацию, обратитесь к модераторам."
    Timestamp: True

  AlreadyVerified:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Ошибка!"
    Description: "Этот пользователь уже верифицирован!"

  NotVerified:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Ошибка!"
    Description: "Этот пользователь не найден в списке верифицированных."

  MentionHelp:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "Список команд (mention)"
    Description: "<:owner:1273932655028605060> `{prefix}mention add` ┊ Установить канал для упоминания новых пользователей \n<:owner:1273932655028605060> `{prefix}mention set` ┊ Изменить канал для упоминания новых пользователей \n<:owner:1273932655028605060> `{prefix}mention remove` ┊ Удалить канал для упоминания новых пользователей"

  MentionAdd:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:tick:1272260155190546584> Успех!"
    Description: "Упоминания новых пользователей будут отправляться в канал {channel-mention}"

  MentionAlreadyAdded:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Ошибка!"
    Description: "Этот канал уже привязан для упоминаний новых пользователей!"

  MentionDelete:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:tick:1272260155190546584> Успех!"
    Description: "Канал для упоминания новых пользователей был удален"

  NoMentionChannel:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Ошибка!"
    Description: "Канал для упоминания новых пользователей не найден"

  MentionSet:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:checkmark:1272260131677278208> Успех!"
    Description: "Канал для упоминания новых пользователей изменен на {channel-mention}"

  NoPermissions:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Отсутствуют права!"
    Description: "У вас нет прав для выполнения этой команды."

  SelfVerifyError:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Ошибка!"
    Description: "Вы не можете верифицировать самого себя."
    Timestamp: True

  SelectRole:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:roles:1274285161256718429> Выберите роль"
    Description: "Пожалуйста, выберите роль, которая будет выдана."
    Timestamp: True

  RoleNotFound:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Ошибка!"
    Description: "Роль, которую вы пытаетесь удалить, не найдена на сервере. Пожалуйста, убедитесь, что роль существует и попробуйте снова."
    Timestamp: True

  AutoBanVerifyRejection:
    Author: "{bot-displayname}"
    AuthorIcon: "{bot-pfp}"
    Title: "<:crossmark:1272260131677278209> Превышен лимит отказов!"
    Description: "К сожалению, вам был выдан отказ в проверке из-за превышения допустимого количества отказов."
    Timestamp: True

  LogVerifySuccess:
    Title: "Пользователь Верифицирован"
    Description: "<:arrow:1274280332304322611> **Ответственный**: {verify-moderator} `{verify-moderator-id}`\n<:arrow:1274280332304322611> **Цель**: {user-mention} `{user-id}`\n<:arrow:1274280332304322611> **Роль**: <@&{verify-role}> `{verify-role}`\n<:arrow:1274280332304322611> {verify-date}"

  LogVerifyRejection:
    Title: "Недопуск Пользователя"
    Description: "<:arrow:1274280332304322611> **Ответственный**: {verify-lastmoderator} `{verify-lastmoderator-id}`\n<:arrow:1274280332304322611> **Цель**: {user-mention} `{user-id}`\n<:arrow:1274280332304322611> {verify-lastdate}"

  LogVerifyCancelled:
    Title: "Верификация Отменена"
    Description: "<:arrow:1274280332304322611> **Ответственный**: {verify-lastmoderator} `{verify-lastmoderator-id}`\n<:arrow:1274280332304322611> **Цель**: {user-mention} `{user-id}`\n<:arrow:1274280332304322611> {verify-lastdate}"

  LogVerifyRemoved:
    Title: "Верификация Удалена"
    Description: "<:arrow:1274280332304322611> **Ответственный**: {verify-lastmoderator} `{verify-lastmoderator-id}`\n<:arrow:1274280332304322611> **Цель**: {user-mention} `{user-id}`\n<:arrow:1274280332304322611> {verify-lastdate}"

  LogAutoBanRejection:
      Title: "Превышен лимит отказов"
      Description: "<:arrow:1274280332304322611> **Цель**: {user-mention} `{user-id}`\n<:arrow:1274280332304322611> **Отказы**: `{verify-rejection}`"